# Generated by Django 3.0.5 on 2020-05-15 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='sample',
            name='row',
            field=models.IntegerField(),
        ),
    ]
