# Generated by Django 3.0.5 on 2020-07-20 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_auto_20200706_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='row',
            field=models.CharField(max_length=10),
        ),
    ]
