# Generated by Django 3.0.5 on 2020-07-20 08:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0004_remove_assay_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
