# Generated by Django 3.0.5 on 2020-07-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_study_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='assays',
            field=models.ManyToManyField(related_name='dnas', through='registry.Sample', to='registry.Assay'),
        ),
    ]
