# Generated by Django 3.0.5 on 2020-07-20 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_dna_assays'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
