# Generated by Django 3.0.5 on 2020-07-26 03:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0007_study_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='shared_with',
            field=models.ManyToManyField(blank=True, default=[], related_name='shared_studies', to=settings.AUTH_USER_MODEL),
        ),
    ]
