# Generated by Django 3.0.5 on 2020-07-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20200720_1652'),
        ('registry', '0007_study_public'),
    ]

    operations = [
    ]
