# Generated by Django 3.0.5 on 2020-07-27 14:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_auto_20200726_0333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dna',
            name='sboluris',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), blank=True, default=[], size=None),
        ),
        migrations.AlterField(
            model_name='study',
            name='doi',
            field=models.URLField(blank=True),
        ),
    ]
