# Generated by Django 3.0.5 on 2020-07-27 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_merge_20200726_0114'),
        ('registry', '0009_auto_20200726_0333'),
    ]

    operations = [
    ]
