# Generated by Django 3.0.5 on 2020-07-27 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_merge_20200727_0209'),
        ('registry', '0011_auto_20200727_1437'),
    ]

    operations = [
    ]
