# Generated by Django 3.0.5 on 2020-07-29 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_merge_20200727_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentration', models.FloatField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Vector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='dna',
            name='names',
        ),
        migrations.RemoveField(
            model_name='dna',
            name='sboluris',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='dna',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='inducer',
        ),
        migrations.AddField(
            model_name='dna',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dna',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.DeleteModel(
            name='Inducer',
        ),
        migrations.AddField(
            model_name='vector',
            name='dnas',
            field=models.ManyToManyField(related_name='vectors', to='registry.Dna'),
        ),
        migrations.AddField(
            model_name='sample',
            name='supplements',
            field=models.ManyToManyField(related_name='samples', to='registry.Supplement'),
        ),
        migrations.AddField(
            model_name='sample',
            name='vector',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='registry.Vector'),
            preserve_default=False,
        ),
    ]
