# Generated by Django 3.0.5 on 2020-07-30 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_auto_20200729_0235'),
    ]

    operations = [
        migrations.AddField(
            model_name='vector',
            name='name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
