# Generated by Django 3.0.5 on 2020-08-07 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_supplement_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='color',
            field=models.CharField(default='', max_length=6),
        ),
    ]
