# Generated by Django 3.0.5 on 2020-08-07 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0016_signal_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='media',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Media'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='strain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Strain'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='vector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='registry.Vector'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
    ]
