# Generated by Django 3.0.5 on 2020-08-09 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_auto_20200807_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='pubchemid',
            field=models.IntegerField(null=True),
        ),
    ]
