# Generated by Django 3.0.5 on 2020-08-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_chemical_pubchemid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vector',
            name='dnas',
            field=models.ManyToManyField(null=True, related_name='vectors', to='registry.Dna'),
        ),
    ]
