# Generated by Django 3.0.5 on 2020-08-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0021_auto_20200811_1615'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dna',
            name='assays',
        ),
        migrations.AlterField(
            model_name='vector',
            name='dnas',
            field=models.ManyToManyField(related_name='vectors', to='registry.Dna'),
        ),
    ]
