# Generated by Django 3.0.5 on 2020-08-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0022_auto_20200812_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='row',
            field=models.IntegerField(),
        ),
    ]
