# Generated by Django 3.0.5 on 2020-08-14 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0024_auto_20200813_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assay',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='chemical',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='dna',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='measurement',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='media',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='sample',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='supplement',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='vector',
            name='owner',
        ),
    ]
