# Generated by Django 3.0.5 on 2020-08-19 05:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('registry', '0025_auto_20200814_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='dna',
            name='owner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='dnas', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
