# Generated by Django 3.0.5 on 2022-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0028_auto_20200819_0529'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
    ]
