# Generated by Django 3.0.5 on 2022-11-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0029_study_sboluri'),
    ]

    operations = [
        migrations.AddField(
            model_name='assay',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='media',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='supplement',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='vector',
            name='sboluri',
            field=models.URLField(blank=True),
        ),
    ]
